apiVersion: v1
kind: Pod
metadata: 
  name: fresco-nginx-pod
spec:
  volumes:
    - name: fresco-vol
      secret:
        secretName: fresco-secret
    - name: fresco-pvc
      persistentVolumeClaim:
        claimName: fresco-pvc
  containers:
    - name: fresco-nginx-pod
      image: nginx
      volumeMounts:
        - name: fresco-vol
          mountPath: "etc/test"
        - name: fresco-pvc
          mountPath: "/usr/share/nginx/html"
      env:
        - name: SERVER_URL_ENV
          valueFrom:
            configMapKeyRef:
              name: fresco-config
              key:  SERVER_URL
